# Set docker-compose version
version: '3'
networks:
  postgres_db_networks:
    external: true
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && rm -f /usr/local/var/postgres/postmaster.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hospital_management
      - ~/.ssh:/root/.ssh
    environment:
      - PGHOST=postgresql
      - PGUSER=postgres
    networks:
      - postgres_db_networks