# Set docker-compose version
version: '3'
networks:
  postgres_db_networks:
    external: true

services:
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/hospital_management
    ports:
      - "127.0.0.1:3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - postgres_db_networks

  web:
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && rm -f /usr/local/var/postgres/postmaster.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hospital_management
      - ~/.ssh:/root/.ssh
    environment:
      - PGUSER=postgres
      - PGHOST=postgresql
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    networks:
      - postgres_db_networks
    depends_on:
      - webpacker

  